### ISSUE TITLE
`youtube-dl` fails with `ERROR: giving up after 10 fragment retries`

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#1080]
<details><summary>Verbose log</summary>

```
$ youtube-dl --verbose lkBgLv9hGqc 
[debug] System config: []    
[debug] User config: []     
[debug] Custom config: []    
[debug] Command-line args: ['--verbose', 'lkBgLv9hGqc'] 
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17 
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.14.0-1058-oem-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2    
[debug] Proxy map: {} 
[youtube] lkBgLv9hGqc: Downloading webpage    
[youtube] lkBgLv9hGqc: Downloading player 57c75fa4
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1679, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)  
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1651, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)     
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1620, in _extract_n_function_name
    nfunc_and_idx = self._search_regex(    
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1013, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)    
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl
.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)      
[debug] Default format spec: bestvideo+bestaudio/best    
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://rr5---sn-5uaezns7.googlevideo.com/videoplayback?expire=1725051746&ei=At_RZpnlF4Ooy_sP0ImB6AE&ip=2601%3Ac7%3Ac200%3A941%3A0%3A0%3A0%3A1a&id=o-AF97FsJfTHQBTuHCV_3VRPC
6UNQiCufIpOBw6yaggmcq&itag=135&aitags=134%2C135%2C160%2C243&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=QL&mm=31%2C26&mn=sn-5uaezns7%2Csn-p5qlsnrr&ms=au%2Conr&mv=m&mvi=5&pl=30&initcwndbps=107000
0&bui=AQmm2ewl7CP2cgcG5GYhHlNQ3lghqxZVlWAljpxyCHyKxLhgUOS9Dxbpa4Rlu6O0H3094WPMkPSC1aRj&spc=Mv1m9qNB2_G_p-29YGP2pOB1IVG1pLV_4LbwI3s2JPuG6C667hDupy1kJw61&vprv=1&svpuc=1&mime=video%2Fmp4&ns=VbzH2FMqyJk4lZZDD
Nqp_koQ&rqh=1&gir=yes&clen=27629405&dur=384.000&lmt=1697846227708179&mt=1725029818&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=1318224&n=RkAUBlan7JcBmzV&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequire
ssl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABPmVW0wRQIgPQ3SPSspc5zMkh_eXET8aTQezoI8ESVRrzOim33wsecCIQCn7i
OiIRjrKiyYbBm7EOG1y5nAK2K5OYEYvkvcCaBT3w%3D%3D&sig=AJfQdSswRAIgd4yQHABWjeWHR0TV33Pt41z1MTKXfT_1gPgXboGZVwICIFz0Ba47t5hhxWz612dZeO4WOfSmcJSTqFwZLmxq1hph'
[dashsegments] Total fragments: 3                                                                     
[download] Destination: Kajsa Bergqvist Tribute-lkBgLv9hGqc.f135.mp4
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 10 of 10)... 
ERROR: giving up after 10 fragment retries
  File "/home/n130s/.local/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2088, in download
    res = self.extract_info(
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 818, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 825, in wrapper 
    return func(self, *args, **kwargs)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 857, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 891, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1701, in process_video_result
    self.process_info(new_info)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1987, in process_info
    partial_success = dl(fname, new_info)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1932, in dl
    return fd.download(name, info)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/downloader/common.py", line 376, in download
    return self.real_download(filename, info_dict)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/downloader/dash.py", line 73, in real_download
    self.report_error('giving up after %s fragment retries' % count)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/downloader/common.py", line 175, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 638, in report_error
    self.trouble(error_message, tb)
  File "/home/n130s/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 600, in trouble 
    tb_data = traceback.format_list(traceback.extract_stack())
```
</details>

Tried various formats after showing options with `youtube-dl -F` and choosing an option e.g. `youtube-dl -f 251` but no good.

**Comment by 130s** [comment]
Seems to be an acknowledged issue, but on yt-dlp not youtube-dl though https://github.com/yt-dlp/yt-dlp/issues/7811

Despite the pkg difference, clearly the same issue started being observed sometime in 2023? and the version I use `[debug] youtube-dl version 2021.12.17 ` is older.

```
$ apt-cache policy youtube-dl 
youtube-dl:
  Installed: (none)
  Candidate: 2021.12.17-1
  Version table:
     2021.12.17-1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe i386 Packages

$ which youtube-dl 
/home/n130s/.local/bin/youtube-dl
```

Not sure how it was installed...Maybe that's what https://github.com/kinu-garage/hut_10sqft/issues/790#issuecomment-1606064235 with `pip3 install` did. So I'm just re-running the same command.

```
$ pip3 install \
  git+https://github.com/ytdl-org/youtube-dl.git@master#egg=youtube_dl \
  --force-reinstall
Defaulting to user installation because normal site-packages is not writeable
Collecting youtube_dl
  Cloning https://github.com/ytdl-org/youtube-dl.git (to revision master) to /tmp/pip-install-exx4piw5/youtube-dl_f4ec83e3044441dba40e2bb33eae8bf1
  Running command git clone --filter=blob:none --quiet https://github.com/ytdl-org/youtube-dl.git /tmp/pip-install-exx4piw5/youtube-dl_f4ec83e3044441dba40e2bb33eae8bf1
Enter passphrase for key '/home/n130s/.ssh/id_rsa': 
Enter passphrase for key '/home/n130s/.ssh/id_rsa': 
Enter passphrase for key '/home/n130s/.ssh/id_rsa': 
Enter passphrase for key '/home/n130s/.ssh/id_rsa': 
  Resolved https://github.com/ytdl-org/youtube-dl.git to commit c5098961b04ce83f4615f2a846c84f803b072639
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: youtube_dl
  Building wheel for youtube_dl (setup.py) ... done
  Created wheel for youtube_dl: filename=youtube_dl-2021.12.17-py2.py3-none-any.whl size=1969911 sha256=078ab69d88f2a49a0908a8dbcf118acbdef7737616a578f6136b8a4cc1c23664
  Stored in directory: /tmp/pip-ephem-wheel-cache-qh019st9/wheels/b8/03/62/9c414b89a26da510b0a6d984b0ba74200d591e3d0abfa72aa8
Successfully built youtube_dl
Installing collected packages: youtube_dl
  Attempting uninstall: youtube_dl
    Found existing installation: youtube-dl 2021.12.17
    Uninstalling youtube-dl-2021.12.17:
      Successfully uninstalled youtube-dl-2021.12.17
Successfully installed youtube_dl-2021.12.17
```

It just re-installed the same old version :/

https://github.com/yt-dlp/yt-dlp/wiki/Installation shows an update cmd
```
$ yt-dlp -U
Command 'yt-dlp' not found, but can be installed with:
sudo snap install yt-dlp  # version 2024.07.25-2-g28d485714, or
sudo apt  install yt-dlp  # version 2022.04.08-1
See 'snap info yt-dlp' for additional versions.
```

Suprising. `snap` version is the most uptodate.
```
$ sudo snap install yt-dlp
yt-dlp 2024.07.25-2-g28d485714 from Graham Morrison (degville) installed

$ which yt-dlp 
/snap/bin/yt-dlp
```

`yt-dlp 2024.07.25-2` did the trick. I'm switching from `youtube-dl` to `yt-dlp`.

How can I uninstall a `pip3` ver?

```
$ pip3 uninstall git+https://github.com/ytdl-org/youtube-dl.git@master#egg=youtube_dl 
Found existing installation: youtube-dl 2021.12.17
Uninstalling youtube-dl-2021.12.17:
  Would remove:
    /home/n130s/.local/bin/youtube-dl
    /home/n130s/.local/lib/python3.10/site-packages/youtube_dl-2021.12.17.dist-info/*
    /home/n130s/.local/lib/python3.10/site-packages/youtube_dl/*
Proceed (Y/n)? 
  Successfully uninstalled youtube-dl-2021.12.17
```
