### ISSUE TITLE
catkin_tools on USB fails building

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#283]
```
$ ll
total 8900
drwx------  6 auser auser   16384 Apr  5 09:47 ./
drwxr-x---+ 3 root     root        4096 Apr  5 09:45 ../
drwx------  7 auser auser   16384 Apr  5 09:47 cws_s

$ cd /media/auser/9132-7624/cws_s
$ catkin b
:
[build] Found '9' packages in 0.0 seconds.                                                                                                                                                                 
[build] Package table is up to date.                                                                                                                                                                       
Warning: generated devel space setup files have been deleted.
Starting  >>> catkin_tools_prebuild                                                                                                                                                                        
___________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << catkin_tools_prebuild:cmake /media/auser/9132-7624/cws_po/logs/catkin_tools_prebuild/build.cmake.001.log                                                                             
Traceback (most recent call last):
  File "/media/auser/9132-7624/cws_po/build/catkin_tools_prebuild/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/media/auser/9132-7624/cws_po/devel/.private/catkin_tools_prebuild/env.sh')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/catkin/environment_cache.py", line 61, in generate_environment_script
    output = subprocess.check_output([env_script, sys.executable, '-c', python_code])
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
CMake Error at /opt/ros/indigo/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/media/auser/9132-7624/cws_po/build/catkin_tools_prebuild/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/indigo/share/catkin/cmake/all.cmake:186 (safe_execute_process)
  /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)


cd /media/auser/9132-7624/cws_po/build/catkin_tools_prebuild; catkin build --get-env catkin_tools_prebuild | catkin env -si  /usr/bin/cmake /media/auser/9132-7624/cws_po/build/catkin_tools
_prebuild --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/media/auser/9132-7624/cws_po/devel/.private/catkin_tools_prebuild -DCMAKE_INSTALL_PREFIX=/media/auser/9132-7624/cws_po/install; cd -
...........................................................................................................................................................................................................
Failed     << catkin_tools_prebuild:cmake              [ Exited with code 1 ]                                                                                                                              
Failed    <<< catkin_tools_prebuild                    [ 0.6 seconds ]                                                                                                                                     
Abandoned <<< abb_irb1600_6_145_support                [ Unrelated job failed ]
```
Not sure if related but I noticed that `chmod 755 -R` doesn't change the permission in the sub folders.

**Comment by 130s** [comment]
Type of filesystem matters? https://answers.ros.org/question/258287/workspace-on-usb-or-package-on-usb/

**Comment by 130s** [comment]
Maybe hitting https://askubuntu.com/questions/17540/how-do-i-set-executable-permissions-on-a-removable-drive

I don't want to rush changing udev rule right now.

**Comment by 130s** [comment]
```
$ df -T
Filesystem     Type     1K-blocks     Used Available Use% Mounted on
:
/dev/sdc1      vfat      30017184 10031216  19985968  34% /media/auser/9132-7624
```
So maybe we should reformat filesystem, combined with [an answer](https://answers.ros.org/question/258287/workspace-on-usb-or-package-on-usb/?answer=258291#post-id-258291).

**Comment by 130s** [comment]
I personally moved on to `ament/colcon` regarding ros build system.
