### ISSUE TITLE
z-way controller says it's set to EU frequency

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#417]
I'm about to finally give up z-way z-wave controller due to too bad connection https://github.com/130s/hut_10sqft/issues/406.

As https://github.com/130s/hut_10sqft/issues/406#issuecomment-590160234, I found the z-way device' frequency is set to EU, and no US option is available.

# CoS
- [x] Tried factory reset z-way server -> https://github.com/130s/hut_10sqft/issues/417#issuecomment-592994182
- [ ] See if re-installation of z-way server fixes.

**Comment by 130s** [comment]
Factory reset the z-way server (through its web admin page) didn't offer an option to switch to US.

**Comment by 130s** [comment]
Re-installing z-way referencing to https://github.com/130s/hut_10sqft/issues/404#issuecomment-569489100
```
sudo rm -fr /etc/init.d/z-way-server
sudo rm -fr /opt/z-way-server/
sudo apt-get purge z-way* zbw && sudo apt-get autoremove
sudo reboot

sudo apt-get install z-way-full
wget 'http://find.z-wave.me/zbw_new_user?box_type=razberry' -O /tmp/zbw_connect_setup.run && sudo bash /tmp/zbw_connect_setup.run -y && sudo /etc/init.d/zbw_connect start
sudo apt-get install zbw
```
I do see some z- proccesses are running but the web site http://noooodle-rpi2.local:8083/ seems to be 404.

Doing it again :/
```
sudo apt-get purge z-way* zbw && sudo apt-get autoremove
sudo rm -fr /etc/init.d/z-way-server
sudo rm -fr /etc/z-way
sudo rm -fr /opt/z-way-server/

sudo apt-get update && sudo apt-get dist-upgrade  # Nothing got installed

find / -iname z-wave 2> /dev/null                                                
find / -iname zwave 2> /dev/null                                                 
find / -iname zway 2> /dev/null                                                  
find / -iname z-way 2> /dev/null                                                 
/etc/z-way
more /etc/z-way/VERSION
v3.0.4
sudo rm -fr /etc/z-way

sudo reboot

sudo apt-get install z-way-full
wget 'http://find.z-wave.me/zbw_new_user?box_type=razberry' -O /tmp/zbw_connect_setup.run && sudo bash /tmp/zbw_connect_setup.run -y && sudo /etc/init.d/zbw_connect start
``` 
This time it seems to be working. This time I was asked for configs, then I chose package maintenance version, to make difference from previous runs.

```
sudo apt-get install zbw

n130s@130s-rpi2:~ $ more /etc/z-way/box_type.dpkg-new
razberry
n130s@130s-rpi2:~ $ sudo apt-get install zbw
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  zbw
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
15 not fully installed or removed.
Need to get 0 B/4,740 B of archives.
After this operation, 36.9 kB of additional disk space will be used.
(Reading database ... 62063 files and directories currently installed.)
Preparing to unpack .../apt/archives/zbw_1.2_all.deb ...
cat: /etc/z-way/box_type: No such file or directory
Stopping zbw_connect (via systemctl): zbw_connect.service.
Unpacking zbw (1.2) ...
Setting up libdbus-1-dev:armhf (1.10.28-0+deb9u1) ...
Setting up libev4 (1:4.22-1) ...
Setting up libuv1:armhf (1.18.0-3~bpo9+1) ...
Processing triggers for install-info (6.3.0.dfsg.1-1+b1) ...
Setting up libavahi-common-dev:armhf (0.6.32-2) ...
Setting up libavahi-client-dev:armhf (0.6.32-2) ...
Setting up sharutils (1:4.15.2-2+deb9u1) ...
Setting up libavahi-compat-libdnssd1:armhf (0.6.32-2) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Processing triggers for systemd (232-25+deb9u12) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libc-ares2:armhf (1.14.0-1~bpo9+1) ...
Setting up liblzo2-2:armhf (2.08-1.2) ...
Setting up libwebsockets8:armhf (2.0.3-2+b1~rpt1) ...
Setting up libarchive13:armhf (3.2.2-2+deb9u2) ...
Setting up libavahi-compat-libdnssd-dev:armhf (0.6.32-2) ...
Setting up z-way-server (3.0.4) ...
Setting default automation config
Usage: ./z-cfg-update <filename>
Starting z-way-server: done.
Setting up webif (1.1) ...
Starting mongoose (via systemctl): mongoose.service.
Setting up zbw (1.2) ...

Configuration file '/etc/zbw/userid'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** userid (Y/I/N/O/D/Z) [default=N] ? Y
Installing new version of config file /etc/zbw/userid ...

Configuration file '/etc/zbw/passwd'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** passwd (Y/I/N/O/D/Z) [default=N] ? Y
Installing new version of config file /etc/zbw/passwd ...

Configuration file '/etc/zbw/local_port'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** local_port (Y/I/N/O/D/Z) [default=N] ? Y
Installing new version of config file /etc/zbw/local_port ...
zbw_autosetup.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable zbw_autosetup
Starting zbw_connect (via systemctl): zbw_connect.service.
Setting up z-way-full (1.0-latest-version) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Processing triggers for systemd (232-25+deb9u12) ...
Updating FireMotD available updates count ... 2020-02-29 14:28:26,330: FireMotD: Error: Template folder doesn't exist. Upgrading from an older version? Please run make again or run the install function "F
ireMotD -I -v".
```

However I don't see to see `US` again in the

Giving up RazBerry, at least on RPi2. Maybe try RPi3 or 4 in the future.

**Comment by 130s** [comment]
Cont'd a bit more. I found ZMESerialUpdater is available online but no good.
```
$ wget 'https://z-wave.me/download/ZMESerialUpdater' -O ZMESerialUpdater && chmod 755 ZMESerialUpdater
$ ./ZMESerialUpdater
-bash: ./ZMESerialUpdater: cannot execute binary file: Exec format error            
$ ./ZMESerialUpdater serialapi_uzbupdate -fr US -d /dev/ttyAMA0
-bash: ./ZMESerialUpdater: cannot execute binary file: Exec format error            
```

Then I found an instruction. https://z-wave.me/zmeserialupdater-manual/
```
# Download firmware upgrade files you need
# To browse files see https://service.z-wave.me/expertui/uzb-stats/versions-graph.html and click on nodes to get file names
## wget https://service.z-wave.me/expertui/uzb/bootloader_Razberry_from_05_04_to_8aaa_2MB.bin
wget https://service.z-wave.me/expertui/uzb/UPD_FIRMWARE_Razberry_STATIC_2ch_ZME_05_24_04000002_ZME_05_1b_04000002.bin

# Do the update and frequency change
##./ZMESerialUpdater serialapi_uzbupdate -d /dev/ttyAMA0 -b bootloader_Razberry_from_05_04_to_8aaa_2MB.bin -f UPD_FIRMWARE_Razberry500_from_05_04_to_05_07.bin
##./ZMESerialUpdater serialapi_uzbupdate -d /dev/ttyAMA0 -f UPD_FIRMWARE_Razberry_from__05_07__to__05_17.bin
./ZMESerialUpdater serialapi_uzbupdate -d /dev/ttyAMA0 -f UPD_FIRMWARE_Razberry_STATIC_2ch_ZME_05_24_04000002_ZME_05_1b_04000002.bin
```
https://service.z-wave.me/expertui/uzb-stats/versions-graph.html shows 5.36 the newwest but https://forum.z-wave.me/viewtopic.php?t=31599 says 5.36 is dis continued so I chose 5.27.

Then, the last command never ended, so forcefully killed.
```
-->
-->
-->
-->
^CTraceback (most recent call last):
  File "ZMESerialUpdater.py", line 2205, in <module>
  File "ZMESerialUpdater.py", line 2199, in Main
  File "ZMESerialUpdater.py", line 1763, in serial_api_updateUZBfunc
  File "ZMESerialUpdater.py", line 1737, in waitForSerialDev
KeyboardInterrupt
[17579] Failed to execute script ZMESerialUpdater
```

**Comment by 130s** [comment]
```
$ ./ZMESerialUpdater serialapi_freq -d /dev/ttyAMA0 US


                                        Z-WAVE Serial API Tool
                                             Version:LWE0.9
                                             by Z-WAVE>ME


Openning port                            ..............................                        FAILED

        Error  0 Unknown exception:global name 'Programmer' is not defined
```

**Comment by 130s** [comment]
There's Razberry2, which has 4+ out of 5 stars on amazon.com, but [this 1-star review](https://www.amazon.com/gp/customer-reviews/R2AHRV3QJCCV1S/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B01M3Q764U) describes a familiar issue so I'll stay away from razberry2.
>  Hate to give things one star, but the software distribution requires you to install either to an obsolete rasbian distribution, or side install an old version of the ssl library on the current one. Web site has almost no support outside of the forums. Came claiming to be on "RU" frequency, even after finding the magic key to set it to US, it doesn't complete any device interviews with Leviton and Honeywell switches around 5 feet away.
