### ISSUE TITLE
Set up z-wave controller and server, connect z-wave devices

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#610]
Cont'ed from https://github.com/130s/hut_10sqft/issues/418, part of https://github.com/130s/hut_10sqft/issues/401

CoS
1. [x] Chose which computer to serve as a device controller + server.
1. [x] Confirmed z-wave emitting from this server.
1. [x] A z-wave client device connected

**Comment by 130s** [comment]
> -  Chose which computer to serve as a device controller + server.

As of today I only have rpi2 or rpi3-1 running and the latter is HoA server for now https://github.com/130s/hut_10sqft/issues/552 so use rpi2. Not sure how much busy a z-wave device controller computer will become. Depending on the performance need I can switch to a newer rpi host in the future.

**Comment by 130s** [comment]
```
rpi2:~ $ lsusb
Bus 001 Device 004: ID 10c4:8a2a Cygnal Integrated Products, Inc.
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
According to https://zwaveguide.com/the-ultimate-guide-to-z-wave-usb-sticks/, my stick is made by `Cygnal`.
```
rpi2:~ $ ll /dev/ttyUSB*
crw-rw---- 1 root dialout 188, 0 Nov 25 07:09 /dev/ttyUSB0
crw-rw---- 1 root dialout 188, 1 Nov 25 07:09 /dev/ttyUSB1
```

> > * Chose which computer to serve as a device controller + server.
> 
> As of today I only have rpi2 or rpi3-1 running and the latter is HoA server for now #552 so use rpi2. Not sure how much busy a z-wave device controller computer will become. Depending on the performance need I can switch to a newer rpi host in the future.

Then I just found out in the same link, for integrating z-wave into HoA, the device might have to be local.

> After you find the configuration file, you need to put the z-wave stick device name in the configuration. The configuration looks as follows:
> ```
> zwave:
>   usb_path: /dev/ttyACM0
>   device_config: !include zwave_device_config.yaml
> ```

So plugging in the stick into rpi3-1. There, I see them (`lsusb` not available on `Ubuntu Core` :-(

```
rpi3-1@localhost:~$ lsusb

rpi3-1@localhost:~$ ll /dev/ttyUSB*
crw-rw---- 1 root dialout 188, 0 Nov 25 12:40 /dev/ttyUSB0
crw-rw---- 1 root dialout 188, 1 Nov 25 12:40 /dev/ttyUSB1

rpi3-1@localhost:~$ date
Thu Nov 25 12:42:36 UTC 2021
```

Struggled to edit the config file locally (rel. https://github.com/130s/hut_10sqft/issues/475#issuecomment-979192686), I made an updated `configuration.yml` on my laptop and `scp`ed -> `sudo mv`ed.

<details><summary>configuration.yml</summary>

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zwave:
  usb_path: /dev/ttyUSB0
  device_config: !include zwave_device_config.yaml

```
</details>

```
sudo mv ./configuration.yaml /writable/system-data/var/snap/home-assistant-snap/425/configuration.yaml

:

rpi3-1@localhost:~$ sudo systemctl status snap.home-assistant-snap.home-assistant-snap.service
● snap.home-assistant-snap.home-assistant-snap.service - Service for snap application home-assistant-snap.home-assistant-snap
   Loaded: loaded (/etc/systemd/system/snap.home-assistant-snap.home-assistant-snap.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-11-23 13:39:02 UTC; 1 day 23h ago
 Main PID: 23799 (bash)
    Tasks: 18 (limit: 1732)
   CGroup: /system.slice/snap.home-assistant-snap.home-assistant-snap.service
           ├─23799 bash /snap/home-assistant-snap/425/bin/plug-bin /snap/home-assistant-snap/425/bin/hass --config /var/snap/home-assistant-snap/425
           └─23826 python3 /snap/home-assistant-snap/425/bin/hass --config /var/snap/home-assistant-snap/425

Nov 25 12:40:23 localhost home-assistant-snap.home-assistant-snap[23799]:   File "/snap/home-assistant-snap/425/lib/python3.8/site-packages/homeassistant/components/usb/__init__.py", line 213, in scan_serial
Nov 25 12:40:23 localhost home-assistant-snap.home-assistant-snap[23799]:     self.hass.add_job(self._async_process_ports, comports())
Nov 25 12:40:23 localhost home-assistant-snap.home-assistant-snap[23799]:   File "/snap/home-assistant-snap/425/lib/python3.8/site-packages/serial/tools/list_ports_linux.py", line 102, in comports
Nov 25 12:40:23 localhost home-assistant-snap.home-assistant-snap[23799]:     for info in [SysFS(d) for d in devices]
Nov 25 12:40:23 localhost home-assistant-snap.home-assistant-snap[23799]:   File "/snap/home-assistant-snap/425/lib/python3.8/site-packages/serial/tools/list_ports_linux.py", line 102, in <listcomp>
Nov 25 12:40:23 localhost home-assistant-snap.home-assistant-snap[23799]:     for info in [SysFS(d) for d in devices]
Nov 25 12:40:23 localhost home-assistant-snap.home-assistant-snap[23799]:   File "/snap/home-assistant-snap/425/lib/python3.8/site-packages/serial/tools/list_ports_linux.py", line 48, in __init__
Nov 25 12:40:23 localhost home-assistant-snap.home-assistant-snap[23799]:     num_if = int(self.read_line(self.usb_device_path, 'bNumInterfaces'))
Nov 25 12:40:23 localhost home-assistant-snap.home-assistant-snap[23799]: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Nov 25 12:59:35 localhost home-assistant-snap.home-assistant-snap[23799]: 2021-11-25 12:59:35 WARNING (SyncWorker_1) [homeassistant.components.ring] Error fetching Ring history data for device 343ea44c3f89: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

rpi3-1@localhost:~$ sudo systemctl restart snap.home-assistant-snap.home-assistant-snap.service
```

Then Lovelace shows error:
```
2021-11-25 13:09:24 ERROR (MainThread) [homeassistant.bootstrap] Failed to parse configuration.yaml: in "/var/snap/home-assistant-snap/425/configuration.yaml", line 14, column 18: Unable to read file /var/snap/home-assistant-snap/425/zwave_device_config.yaml.. Activating safe mode
```
So commented out that line. I don't have anything I want to configure in `zwave_device_config.yaml` yet anyway.
```
:
#  device_config: !include zwave_device_config.yaml
```

That error went away but got a new one in `Configuration`.
```
Error setting up entry Z-Wave (import from configuration.yaml) for zwave

Logger: homeassistant.config_entries
Source: components/zwave/__init__.py:396
First occurred: 8:14:34 AM (1 occurrences)
Last logged: 8:14:34 AM

Error setting up entry Z-Wave (import from configuration.yaml) for zwave
Traceback (most recent call last):
  File "/snap/home-assistant-snap/425/lib/python3.8/site-packages/openzwave/option.py", line 75, in __init__
    raise ZWaveException(u"Can't write to device %s : %s" % (device, traceback.format_exception(*sys.exc_info())))
openzwave.object.ZWaveException: "Zwave Generic Exception : Can't write to device /dev/ttyUSB0 : ['NoneType: None\\n']"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/home-assistant-snap/425/lib/python3.8/site-packages/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/snap/home-assistant-snap/425/lib/python3.8/site-packages/homeassistant/components/zwave/__init__.py", line 396, in async_setup_entry
    options = ZWaveOption(
  File "/snap/home-assistant-snap/425/lib/python3.8/site-packages/openzwave/option.py", line 81, in __init__
    raise ZWaveException(u"Error when retrieving device %s : %s" % (device, traceback.format_exception(*sys.exc_info())))
openzwave.object.ZWaveException: 'Zwave Generic Exception : Error when retrieving device /dev/ttyUSB0 : [\'Traceback (most recent call last):\\n\', \'  File "/snap/home-assistant-snap/425/lib/python3.8/site-packages/openzwave/option.py", line 75, in __init__\\n    raise ZWaveException(u"Can\\\'t write to device %s : %s" % (device, traceback.format_exception(*sys.exc_info())))\\n\', \'openzwave.object.ZWaveException: "Zwave Generic Exception : Can\\\'t write to device /dev/ttyUSB0 : [\\\'NoneType: None\\\\\\\\n\\\']"\\n\']'
```

**Comment by 130s** [comment]
https://community.home-assistant.io/t/zwave-generic-error-on-new-install/47708/6

```
$ sudo apt-get install libudev-dev
```
Clearly this doesn't work as I'm on `Ubuntu Core`.

Then still no good.
```
$ sudo snap install libudev-dev
error: snap "libudev-dev" not found
```

https://community.home-assistant.io/t/zwave-generic-error-on-new-install/47708/6?
>  On Raspberry Pi you will need to enable the serial interface in the `raspi-config` tool before you can add Z-Wave to Home Assistant.

Ok trying.

```
$  raspi-config 
-bash: raspi-config: command not found

$ sudo snap install raspi-config
error: snap "raspi-config" not found
```
After `sudo reboot` this error disappeared.

Then, I found z-wave integration is deprecated https://www.home-assistant.io/integrations/zwave/

Recommended now is zwave js  https://www.home-assistant.io/integrations/zwave_js. Integration is failing for now, as its protocol is `ws`, which I'm not familliar with. Giving `ws://%rpi3-1_url%:3000` returns ` Failed to connect `.

**Comment by 130s** [comment]
https://www.home-assistant.io/integrations/zwave_js#advanced-installation-instructions
> The above instructions won’t work if you are using Home Assistant Container, Home Assistant Core, or you don’t want to use the built-in Z-Wave JS Server add-on. Below you’ll find the more detailed set-up instructions that covers all use cases.

Maybe I'm one of those.

https://github.com/zwave-js/zwave-js-server
```
rpi3-1@localhost:~$ npm i @zwave-js/server
-bash: npm: command not found
rpi3-1@localhost:~$ sudo snap install npm
error: snap "npm" not found
rpi3-1@localhost:~$ sudo snap install zwave-js
error: snap "zwave-js" not found
rpi3-1@localhost:~$ sudo snap install zwave-js-server
error: snap "zwave-js-server" not found
```
Found it?
```
rpi3-1@localhost:~$ sudo snap install zwavejs2mqtt
zwavejs2mqtt v5.11.0 from Giaever.online (giaever-online) installed
```
```
ts-node src/bin/server.ts /dev/ttyUSB0
-bash: ts-node: command not found

rpi3-1@localhost:~$ sudo systemctl start run-snapd-ns-zwavejs2mqtt.mnt.mount

$ ps -ef|grep -i socket
rpi3-1    3465  2114  0 13:44 pts/0    00:00:00 grep --color=auto -i socket
```
In the integration's instruction, giving `ws:%RPI_URL%:3000` still "failed to connect". `sudo reboot` again.

**Comment by 130s** [comment]
Still fails after reboot.

**Comment by 130s** [comment]
Will try to follow advanced installation of zwave js https://www.home-assistant.io/integrations/zwave_js#requirements

**Comment by 130s** [comment]
Craving to see z-wave to be enabled, for now I'm switching to z-wave (deprecated) integration.

Pressing "Start Network" in config page, it never seems to finish. Then after reloading page I see "Start Network" is enabled again, telling me starting the network didn't really go well.

Log 
```
2021-11-25 13:46:13.531 Always, OpenZwave Version 1.4.3469 Starting Up
2021-11-25 13:46:31.067 Info, Setting Up Provided Network Key for Secure Communications
2021-11-25 13:46:31.067 Warning, Failed - Network Key Not Set
2021-11-25 13:46:31.068 Info, mgr,     Added driver for controller /dev/ttyUSB0
2021-11-25 13:46:31.068 Info,   Opening controller /dev/ttyUSB0
2021-11-25 13:46:31.068 Info, Trying to open serial port /dev/ttyUSB0 (attempt 1)
2021-11-25 13:46:31.068 Error, ERROR: Cannot open serial port /dev/ttyUSB0. Error code 13
2021-11-25 13:46:31.068 Error, ERROR: Failed to open serial port /dev/ttyUSB0
2021-11-25 13:46:31.068 Warning, WARNING: Failed to init the controller (attempt 0)
2021-11-25 13:46:36.068 Info,   Opening controller /dev/ttyUSB0
2021-11-25 13:46:36.069 Info, Trying to open serial port /dev/ttyUSB0 (attempt 1)
2021-11-25 13:46:36.069 Error, ERROR: Cannot open serial port /dev/ttyUSB0. Error code 13
2021-11-25 13:46:36.069 Error, ERROR: Failed to open serial port /dev/ttyUSB0
2021-11-25 13:46:36.069 Warning, WARNING: Failed to init the controller (attempt 1)
2021-11-25 13:46:41.069 Info,   Opening controller /dev/ttyUSB0
2021-11-25 13:46:41.070 Info, Trying to open serial port /dev/ttyUSB0 (attempt 1)
2021-11-25 13:46:41.070 Error, ERROR: Cannot open serial port /dev/ttyUSB0. Error code 13
2021-11-25 13:46:41.070 Error, ERROR: Failed to open serial port /dev/ttyUSB0
2021-11-25 13:46:41.070 Warning, WARNING: Failed to init the controller (attempt 2)
2021-11-25 13:46:46.070 Info,   Opening controller /dev/ttyUSB0
2021-11-25 13:46:46.070 Info, Trying to open serial port /dev/ttyUSB0 (attempt 1)
2021-11-25 13:46:46.077 Error, ERROR: Cannot open serial port /dev/ttyUSB0. Error code 13
2021-11-25 13:46:46.077 Error, ERROR: Failed to open serial port /dev/ttyUSB0
2021-11-25 13:46:46.077 Warning, WARNING: Failed to init the controller (attempt 3)
2021-11-25 13:46:51.078 Info,   Opening controller /dev/ttyUSB0
2021-11-25 13:46:51.078 Info, Trying to open serial port /dev/ttyUSB0 (attempt 1)
2021-11-25 13:46:51.081 Error, ERROR: Cannot open serial port /dev/ttyUSB0. Error code 13
2021-11-25 13:46:51.082 Error, ERROR: Failed to open serial port /dev/ttyUSB0
2021-11-25 13:46:51.082 Warning, WARNING: Failed to init the controller (attempt 4)
2021-11-25 13:46:51.082 Detail, contrlr, Notification: DriverFailed
```

**Comment by 130s** [comment]
https://community.home-assistant.io/t/zwave-does-not-start/48205/8 suggests a custom `udev` rule is needed??? WTF. That'd make home automation only limited to developers if it's true...

**Comment by 130s** [comment]
Ok I need to follow the configuration https://www.home-assistant.io/integrations/zwave/#detailed-installation-instructions

**Comment by 130s** [comment]
https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/other-methods
```
sudo snap connect zwavejs2mqtt:raw-usb
sudo snap connect zwavejs2mqtt:hardware-observe
```
Then got the following (when following https://github.com/zwave-js/zwavejs2mqtt/discussions/1216#discussion-3364776)
```
$ zwavejs2mqtt.help
Missing plug: «serial-port»
OPTIONAL plug
Connect with: $ sudo snap connect zwavejs2mqtt:serial-port
zwavejs2mqtt - v5.12.0

IMPORTANT! The DAEMON/SERVICE is disabled by default after installation.
You have to manually 'daemonize' it with executing the command

$ zwavejs2mqtt.enable

Set your configuration as descrived below

Server configuration values: {
	"server": {
		"host": "localhost",
		"port": 8091,
		"ssl": false
	}
}

- server.ssl: Use secure communication
- server.host: IP address to bind to, e.g 127.0.0.1
- server.port: Port to reach the web interface

Session configuration values: {
	"session": {
		"cookie-secure": "",
		"secret": "5ecfcd28-4df5-11ec-a929-134b308a84a6"
	}
}

- session.secret: Used as secret for session. If not provided a default one is used.
- session.cookie-secure: Set the cookie secure option. See: https://github.com/expressjs/session#cookiesecure

Session configuration values: {
	"mqtt": {
		"name": ""
	}
}

- mqtt.name: The name used as client name when connecting to the mqtt server.

Set options with:         $ snap set zwavejs2mqtt param=key
For example:              $ snap set zwavejs2mqtt server.host=0.0.0.0

Other settings can be set in the UI after start.

Follow the log with
$ sudo snap logs zwavejs2mqtt -f

Other commands
Disable the daemon:       $ zwavejs2mqtt.disable
Restart the daemon:       $ zwavejs2mqtt.restart
```

Following, I finally seem to have started `zwavejs2mqtt` running.
```
uo130s@localhost:~$ sudo reboot

ssh
$ ps -ef|grep -i zwa
root      1097     1 39 04:11 ?        00:00:05 node /snap/zwavejs2mqtt/260/lib/node_modules/yarn/bin/yarn.js start
root      1375  1097 99 04:12 ?        00:00:04 /snap/zwavejs2mqtt/260/bin/node /snap/zwavejs2mqtt/260/lib/node_modules/zwavejs2mqtt/.yarn/releases/yarn-3.1.0.cjs start
uo130s    1388  1189  0 04:12 pts/0    00:00:00 grep --color=auto -i zwa
uo130s@localhost:~$ sudo snap set zwavejs2mqtt server.host=192.168.1.179
2021-11-30T04:12:12Z INFO task ignored
```
Then http://192.168.1.179:8091/ eventually shows a page. On this page,
1. `/dev/ttyUSB0`
1. Toggle `homeassistant` -> `WS server`. `Server Port` = 3000 (default, no need to change).
1. Click "Save".

Then click "Add Integration" at https://www.home-assistant.io/integrations/zwave_js#advanced-installation-instructions. `WS:%IPADDR%:3000` then voila.

**Comment by 130s** [comment]
Trying to see 2 of Aeotech switches https://github.com/130s/hut_10sqft/issues/251 ([instruction](https://drive.google.com/drive/u/0/folders/1EZmIMO39-QaBkJyxc27FPAfyptN4JKcN)) connects to this z-wave network. So far no good. What I've been doing:
1. Plug a switch to power outlet.
1. Press "action button" on the device. Light starts quickly blinking in bright green.
1. After several seconds, it starts gradient.

http://%IPADDR%:8091/debug
```
2021-11-30 04:42:57.813 INFO GATEWAY: Driver is READY
2021-11-30 04:42:57.817 DEBUG MQTT: Publishing to zwave/driver/status: true with options { qos: 1, retain: true }
2021-11-30 04:42:57.819 INFO ZWAVE: Zwave driver is ready
2021-11-30 04:42:57.819 INFO ZWAVE: Controller status: Driver ready
2021-11-30 04:42:57.835 DEBUG ZWAVE: Binding to node 1 events
2021-11-30 04:42:57.838 DEBUG MQTT: Publishing to zwave/nodeID_1/status: { time: 1638247377837, value: true, status: 'Unknown', nodeId: 1 } with options { qos: 1, retain: true }
2021-11-30 04:42:57.839 DEBUG ZWAVE: Node 1 has been added to nodes array
2021-11-30 04:42:57.841 INFO ZWAVE: Scanning network with homeid: 0xd9b5ad0b
2021-11-30 04:42:57.844 DEBUG MQTT: Publishing to zwave/nodeID_1/status: { time: 1638247377844, value: true, status: 'Alive', nodeId: 1 } with options { qos: 1, retain: true }
2021-11-30 04:42:57.845 INFO ZWAVE: Node 1 is alive
2021-11-30 04:42:57.851 DEBUG MQTT: Publishing to zwave/nodeID_1/status: { time: 1638247377850, value: true, status: 'Alive', nodeId: 1 } with options { qos: 1, retain: true }
2021-11-30 04:42:57.852 DEBUG ZWAVE: Node 1: mapping absence of CC 128 (Battery) to node property 'isBatteryPowered
2021-11-30 04:42:57.853 INFO ZWAVE: Node 1 ready: Sigma Designs (Former Zensys) - HUSBZB-1 (QuickStick Combo)
2021-11-30 04:42:57.855 INFO ZWAVE: Controller status: Scan completed
2021-11-30 04:42:57.856 INFO ZWAVE: Network scan complete. Found: 1 nodes
2021-11-30 04:42:57.870 INFO ZWAVE-SERVER: ZwaveJS server listening on port 3000
2021-11-30 04:42:58.266 INFO ZWAVE: Next update scheduled for: Wed Dec 01 2021 00:00:00 GMT+0000 (Coordinated Universal Time)
2021-11-30 04:43:00.050 INFO MQTT: MQTT client reconnecting
2021-11-30 04:43:00.056 ERROR MQTT: Mqtt client error connect ECONNREFUSED 127.0.0.1:1883
Error: connect ECONNREFUSED 127.0.0.1:1883
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
2021-11-30 04:43:00.058 INFO MQTT: MQTT client closed
2021-11-30 04:43:03.059 INFO MQTT: MQTT client reconnecting
2021-11-30 04:43:03.065 ERROR MQTT: Mqtt client error connect ECONNREFUSED 127.0.0.1:1883
Error: connect ECONNREFUSED 127.0.0.1:1883
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
2021-11-30 04:43:03.068 INFO MQTT: MQTT client closed
2021-11-30 04:43:06.068 INFO MQTT: MQTT client reconnecting
2021-11-30 04:43:06.074 ERROR MQTT: Mqtt client error connect ECONNREFUSED 127.0.0.1:1883
```

Switched to lovelace, then, I was able to add the switch. From http://192.168.1.179:8123/config/integrations -> `Configure` -> [Manage your Z-Wave Network](http://192.168.1.179:8123/config/zwave_js/dashboard?config_entry=732d9c2da4549fdb28a891c28b0a4922) -> "`Add device`". This puts the z-wave hub into "inclusion mode". Then on the device to be included, start the add mode.
