### ISSUE TITLE
serval: youtube-dl fails: Unhandled exception in decode

### ISSUE THREAD

**Issue by 130s** [kinu-garage/hut_10sqft#790]
```
$ youtube-dl ******** --verbose
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['********', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.9 (CPython) - Linux-6.0.12-76060006-generic-x86_64-with-Ubuntu-22.04-jammy
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11
[debug] Proxy map: {}
[youtube] ********: Downloading webpage
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1524, in _n_descramble
    raise ExtractorError('Unhandled exception in decode')
youtube_dl.utils.ExtractorError: Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 816, in wrapper
    return func(self, *args, **kwargs)
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 837, in __extract_info
    ie_result = ie.extract(url)
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1974, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
```
$ snap info youtube-dl
name:      youtube-dl
summary:   Download videos from youtube.com or other video platforms
publisher: Joe Borg (joeborg)
store-url: https://snapcraft.io/youtube-dl
contact:   https://github.com/joedborg/youtube-dl
license:   unset
description: |
  youtube-dl is a command-line program to download videos from YouTube.com and
  a few more sites. It requires the Python interpreter, version 2.6, 2.7, or
  3.2+, and it is not platform specific. It should work on your Unix box, on
  Windows or on macOS. It is released to the public domain, which means you
  can modify it, redistribute it or use it however you like.
commands:
  - youtube-dl
snap-id:      Tut7kMl7WlcoEStIgSSsVB1E6CIZnibQ
tracking:     latest/stable
refresh-date: 2022-08-26
channels:
  latest/stable:    2021.12.17+git01bf89e 2022-08-26 (4806) 97MB -
  latest/candidate: ↑                                            
  latest/beta:      ↑                                            
  latest/edge:      2021.12.17+git01bf89e 2022-08-26 (4806) 97MB -
installed:          2021.12.17+git01bf89e            (4806) 97MB -

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Comment by 130s** [comment]
Maybe the same issue https://github.com/ytdl-org/youtube-dl/issues/31530?

Seems like fork exists https://github.com/yt-dlp/yt-dlp#installation

**Comment by udippel** [comment]
> latest/beta:      ↑                                            
>   latest/edge:      2021.12.17+git01bf89e 2022-08-26 (4806) 97MB -

I know. I reported the same further up here. But who can be bothered to read, seriously, by 300+ posts. 
Never mind. I stumbled over this myself, thinking the snap-guys were more recent. Do complain with them.
If need be, start reading at the very top here. And if you don't manage, read my posts about *buntu further above. 
And if it still doesn't work, show us the outputs of the commands written there, and I'll try to help you further.

**Comment by 130s** [comment]
Thanks for the comment.
There are 800+ posts and unfortunately I couldn't figure out the very post you're trying to point to. But this one https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1460816709 seems to have worked around the issue for me.

```
pip3 install \
  git+https://github.com/ytdl-org/youtube-dl.git@master#egg=youtube_dl \
  --force-reinstall
```
